[build]
builder = "paketobuildpacks/builder:base"

[build.args]
BP_JVM_VERSION = "17"

[deploy]
start = "java -jar sistema-votacion-backend/target/*.jar"

[project]
root = "sistema-votacion-backend"

