[build]
# Forzamos Java 17 porque Railway lo soporta
builder = "paketobuildpacks/builder:base"

[build.env]
BP_JVM_VERSION = "17"

[deploy]
start = "java -jar target/*.jar"

[experimental]
src = "sistema-votacion-backend"

