services:
  - type: web
    name: sistema-votacion-backend
    env: java
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/sistema-votacion-backend-0.0.1-SNAPSHOT.jar
    envVars:
      - key: JAVA_VERSION
        value: 17
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: SERVER_PORT
        value: 10000
      - key: PGHOST
        sync: false
      - key: PGPORT
        sync: false
      - key: PGDATABASE
        sync: false
      - key: PGUSER
        sync: false
      - key: PGPASSWORD
        sync: false

databases:
  - name: sistema-votacion-db
    databaseName: sistema_votacion
    user: sistema_votacion_user
    plan: free

